# Generated by Django 4.2.5 on 2023-09-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('asset_id', models.IntegerField(unique=True)),
                ('quartex_uid', models.CharField(max_length=36, unique=True)),
                ('quarter_name', models.CharField(max_length=100, unique=True)),
                ('lang', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
