# Generated by Django 5.0.6 on 2024-11-14 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Administrations',
            },
        ),
        migrations.CreateModel(
            name='ControlledSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'New Subjects',
            },
        ),
        migrations.CreateModel(
            name='DocumentGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Document Genres',
            },
        ),
        migrations.CreateModel(
            name='LegacySubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Legacy Subjects',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('asset_id', models.IntegerField(unique=True)),
                ('quartex_uid', models.CharField(max_length=36, unique=True)),
                ('quartex_name', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
                ('lang', models.CharField(blank=True, max_length=3, null=True)),
                ('administration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.administration')),
                ('controlledsubjects', models.ManyToManyField(blank=True, to='documents.controlledsubjects')),
                ('documentgenre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentgenre')),
                ('subjects', models.ManyToManyField(to='documents.legacysubjects')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartex_image_iiif_hash', models.CharField(max_length=36, unique=True)),
                ('order', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
            options={
                'unique_together': {('order', 'document')},
            },
        ),
    ]
