# Generated by Django 4.2.5 on 2023-09-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='quarter_name',
            new_name='quartex_name',
        ),
    ]
