# Generated by Django 4.2.5 on 2023-09-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_quarter_name_document_quartex_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacySubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='subjects',
            field=models.ManyToManyField(to='documents.legacysubjects'),
        ),
    ]
