# Generated by Django 4.2.5 on 2023-09-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_legacysubjects_document_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacysubjects',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
