# Generated by Django 3.2.23 on 2024-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_legacysubjects_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='newsubjects',
            field=models.ManyToManyField(to='documents.NewSubjects'),
        ),
    ]
