# Generated by Django 4.2.5 on 2024-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20240126_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='administration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
