# Generated by Django 5.0.2 on 2024-02-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documentgenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documentgenre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentgenre'),
        ),
    ]
