# Generated by Django 4.2.5 on 2024-02-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_administration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlled_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Administrations',
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='administration',
        ),
        migrations.AddField(
            model_name='document',
            name='administration',
            field=models.ManyToManyField(to='documents.administration'),
        ),
    ]
