# Generated by Django 4.2.5 on 2024-02-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_administration_remove_document_administration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='administration',
        ),
        migrations.AddField(
            model_name='document',
            name='administration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.administration'),
        ),
    ]
