# Generated by Django 5.0.2 on 2024-02-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_documentgenre'),
        ('documents', '0010_remove_document_administration_and_more'),
    ]

    operations = [
    ]
