# Generated by Django 5.0.2 on 2024-03-19 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_merge_20240216_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documentgenre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentgenre'),
        ),
        migrations.AlterField(
            model_name='documentgenre',
            name='name',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='legacysubjects',
            name='name',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='newsubjects',
            name='name',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
