# Generated by Django 5.0.2 on 2024-03-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_rename_controlled_name_administration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsubjects',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
