# Generated by Django 5.0.2 on 2024-03-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_newsubjects_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewSubjects',
            new_name='ControlledSubjects',
        ),
    ]
