# Generated by Django 5.0.2 on 2024-03-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_rename_newsubjects_controlledsubjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='newsubjects',
            new_name='controlledsubjects',
        ),
    ]
