# Generated by Django 5.0.2 on 2024-03-27 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_rename_newsubjects_document_controlledsubjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='controlledsubjects',
        ),
        migrations.AddField(
            model_name='document',
            name='controlledsubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.controlledsubjects'),
        ),
    ]
