# Generated by Django 5.0.2 on 2024-03-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_remove_document_controlledsubjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuartexYN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='quartexyn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.quartexyn'),
        ),
    ]
