# Generated by Django 5.0.6 on 2024-11-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_remove_document_controlledsubjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='controlledsubjects',
            options={'verbose_name_plural': 'New Subjects'},
        ),
        migrations.AddField(
            model_name='document',
            name='quartexyn',
            field=models.BooleanField(default=False, verbose_name='QuartexYN'),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='document',
            name='controlledsubjects',
        ),
        migrations.AddField(
            model_name='document',
            name='controlledsubjects',
            field=models.ManyToManyField(blank=True, to='documents.controlledsubjects'),
        ),
    ]
