# Generated by Django 5.0.6 on 2024-11-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_source_alter_controlledsubjects_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='quartexyn',
        ),
    ]
