# Generated by Django 5.0.2 on 2024-04-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_quartexyn_document_quartexyn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='quartexyn',
            field=models.BooleanField(default=False, verbose_name='QuartexYN'),
        ),
        migrations.DeleteModel(
            name='QuartexYN',
        ),
    ]
