# Generated by Django 5.0.6 on 2024-07-23 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_source_alter_document_controlledsubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.source'),
        ),
    ]
