# Generated by Django 5.0.6 on 2024-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_source_alter_document_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
