# Generated by Django 5.0.6 on 2024-11-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_alter_document_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='quartexyn',
        ),
    ]
