# Generated by Django 5.0.6 on 2024-11-14 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlled_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Areas of Study',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlled_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlled_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlled_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ethnicities',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionDocumentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Institution Document Roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonDocumentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Person Document Roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikipediaGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Wikipedia Grades',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of person, canonical, unformatted')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Year of birth')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Year of death')),
                ('area_of_expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('area_of_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.areaofstudy')),
                ('country_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.country')),
                ('degree_granting_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.institution')),
                ('ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.ethnicity')),
                ('highest_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.degree')),
                ('wikipedia_grade', models.ForeignKey(blank=True, help_text='Please use for PCAST & OSTP members only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.wikipediagrade')),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonDocumentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_member_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.institution')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namedEntities.person')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.persondocumentrole')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPersonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('alice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relation_source', to='namedEntities.person')),
                ('bob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relation_target', to='namedEntities.person')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionDocumentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namedEntities.institution')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.persondocumentrole')),
                ('part_of', models.ForeignKey(blank=True, help_text='Please use only when adding a <b>new</b> institution above.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.sector')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.sector'),
        ),
    ]
