# Generated by Django 4.2.5 on 2023-11-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_alter_legacysubjects_options"),
        ("namedEntities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonDocumentRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="ethnicity",
            options={"verbose_name_plural": "Ethnicities"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
        migrations.RenameField(
            model_name="person",
            old_name="death_date",
            new_name="death_year",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="controlled_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="person",
            name="area_of_exptertise",
        ),
        migrations.AddField(
            model_name="person",
            name="area_of_expertise",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ethnicity",
            name="controlled_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="PersonPersonRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "alice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_relation_source",
                        to="namedEntities.person",
                    ),
                ),
                (
                    "bob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_relation_target",
                        to="namedEntities.person",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonDocumentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "as_member_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="namedEntities.institution",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="namedEntities.person",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="namedEntities.persondocumentrole",
                    ),
                ),
            ],
        ),
    ]
