# Generated by Django 4.2.5 on 2023-11-13 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("namedEntities", "0002_persondocumentrole_personpersonrelation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="ethnicity",
            options={"verbose_name_plural": "Ethnicities"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
        migrations.AlterModelOptions(
            name="persondocumentrole",
            options={"ordering": ["id"]},
        ),
    ]
