# Generated by Django 3.2.23 on 2024-01-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namedEntities', '0003_wikipediagrade_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofstudy',
            options={'verbose_name_plural': 'Areas of study'},
        ),
        migrations.AlterField(
            model_name='person',
            name='wikipedia_grade',
            field=models.ForeignKey(blank=True, help_text='Please use for PCAST & OSTP members only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.wikipediagrade'),
        ),
    ]
