# Generated by Django 4.2.5 on 2024-02-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namedEntities', '0005_auto_20240131_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofstudy',
            options={'verbose_name_plural': 'Areas of Study'},
        ),
        migrations.AlterModelOptions(
            name='persondocumentrole',
            options={'ordering': ['id'], 'verbose_name_plural': 'Person Document Roles'},
        ),
        migrations.AlterModelOptions(
            name='wikipediagrade',
            options={'verbose_name_plural': 'Wikipedia Grades'},
        ),
    ]
