# Generated by Django 5.0.2 on 2024-03-19 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namedEntities', '0007_institutiondocumentrole_institutiondocumentrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiondocumentrelation',
            name='part_of',
            field=models.ForeignKey(blank=True, help_text='Please use only when adding a <b>new</b> institution above.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='namedEntities.sector'),
        ),
    ]
